### ISSUE TITLE
React Emoji Update

### ISSUE THREAD

**Issue by DWMagus** [noprotocolunit/discord_chat_bot#27]
Currently the bot only responds 'OK' when it reads in a message intended for iteself.

Change the initial react emoji to an empty checkbox
Once the bot responds to the command, remove the empty checkbox emoji and then react with a filled checkbox remoji

**Comment by noprotocolunit** [comment]
🟩 - Read and will process the message
✅ - Answered message

**Comment by noprotocolunit** [comment]
- [x] Change current reaction to 🟩 
- [x] Add a second reaction when message completes
- [ ] Remove the original reaction?

**Comment by DWMagus** [comment]
Should be able to just re-react with the same emoji to make it disappear.  If you try doing a 'remove' I believe it does it the way an admin would.

**Comment by noprotocolunit** [comment]
Updates are now in the parameters branch because why not.
