### ISSUE TITLE
Periodic Update Function

### ISSUE THREAD

**Issue by DWMagus** [noprotocolunit/discord_chat_bot#28]
Right now the bot's status information is only updated when it reads in a message meant for itself.

Eventually:
Move status update message to its own function
Call the function whenever the bot receives a message meant for itself in addition to when it responds.

Add a 'cooldown' timer (measure against previous set timer) to make sure it doesn't update more than once every 5 seconds to prevent discord API spam

- [x] Create a function that handles the updating temperature
- [x] Move the current implementation into it
- [x] Fix implementation to add async
- [x] Set it to run on_ready and again in on_message
- [x] Add time constraints

**Comment by DWMagus** [comment]
Updating feature request;

Create a function that updates all the information at the bottom.

Have a variable that stores 'last updated' as a timestamp.  Have another variable to define the 'time period'.
Call the function on every message the bot reads (regardless of whether it acts on it or not), and inside that function if the time since 'last updated' exceeds 'time period', update stuff below and reset 'last updated' to the current timestamp.

Probably should have 'time period' at least 10 seconds so discord isn't spammed.  Probably can get away with every 30 seconds.

- Update current status
- Pull in new files (since this is event-based, it's better than running a loop constantly)
- Pull in any new configuration changes (move config changes to a file and not hardcoded)

Use this function for anything that needs to either be updated on the bot periodically (status, pulling in new config files, other stuff that may eventually need to be updated).

**Comment by DWMagus** [comment]
Function can also be called at bot startup to load everything and modularize code.

**Comment by noprotocolunit** [comment]
Added the 30 seconds wait time.

**Comment by noprotocolunit** [comment]
I did the easy part and will open a discussion for the bigger-than-a-breadbox part.
